"""Form data constants used by damage_panel modules."""
from __future__ import annotations

FORM_POKEAPI_EN: dict[str, str] = {
    # gen 1-3 standard megas (in PokeAPI)
    "メガフシギバナ":           "venusaur-mega",
    "メガリザードンＸ":         "charizard-mega-x",
    "メガリザードンＹ":         "charizard-mega-y",
    "メガカメックス":           "blastoise-mega",
    "メガスピアー":             "beedrill-mega",
    "メガピジョット":           "pidgeot-mega",
    "メガピクシー":             "clefable-mega",
    "メガウツボット":           "victreebel-mega",
    "メガヤドラン":             "slowbro-mega",
    "メガゲンガー":             "gengar-mega",
    "メガスターミー":           "starmie-mega",
    "メガカイロス":             "pinsir-mega",
    "メガギャラドス":           "gyarados-mega",
    "メガプテラ":               "aerodactyl-mega",
    "メガカイリュー":           "dragonite-mega",
    "メガミュウツーＸ":         "mewtwo-mega-x",
    "メガミュウツーＹ":         "mewtwo-mega-y",
    # gen 2 megas
    "メガメガニウム":           "meganium-mega",
    "メガオーダイル":           "feraligatr-mega",
    "メガデンリュウ":           "ampharos-mega",
    "メガハガネール":           "steelix-mega",
    "メガハッサム":             "scizor-mega",
    "メガヘラクロス":           "heracross-mega",
    "メガエアームド":           "skarmory-mega",
    "メガヘルガー":             "houndoom-mega",
    "メガバンギラス":           "tyranitar-mega",
    # gen 3 megas
    "メガジュカイン":           "sceptile-mega",
    "メガバシャーモ":           "blaziken-mega",
    "メガラグラージ":           "swampert-mega",
    "メガヤミラミ":             "sableye-mega",
    "メガクチート":             "mawile-mega",
    "メガボスゴドラ":           "aggron-mega",
    "メガチャーレム":           "medicham-mega",
    "メガライボルト":           "manectric-mega",
    "メガサメハダー":           "sharpedo-mega",
    "メガバクーダ":             "camerupt-mega",
    "メガチルタリス":           "altaria-mega",
    "メガジュペッタ":           "banette-mega",
    "メガチリーン":             "chimecho-mega",
    "メガアブソル":             "absol-mega",
    "メガオニゴーリ":           "glalie-mega",
    "メガボーマンダ":           "salamence-mega",
    "メガメタグロス":           "metagross-mega",
    "メガラティアス":           "latias-mega",
    "メガラティオス":           "latios-mega",
    # gen 4 megas
    "メガルカリオ":             "lucario-mega",
    "メガガブリアス":           "garchomp-mega",
    "メガミミロップ":           "lopunny-mega",
    "メガエルレイド":           "gallade-mega",
    "メガユキメノコ":           "froslass-mega",
    "メガタブンネ":             "audino-mega",
    "メガムクホーク":           "staraptor-mega",
    # gen 4 legendary
    "メガヒードラン":           "heatran-mega",
    # gen 5 megas
    "メガエンブオー":           "emboar-mega",
    "メガドリュウズ":           "excadrill-mega",
    "メガペンドラー":           "scolipede-mega",
    "メガズルズキン":           "scrafty-mega",
    "メガシビルドン":           "eelektross-mega",
    "メガシャンデラ":           "chandelure-mega",
    "メガゴルーグ":             "golurk-mega",
    # gen 6 megas
    "メガブリガロン":           "chesnaught-mega",
    "メガマフォクシー":         "delphox-mega",
    "メガゲッコウガ":           "greninja-mega",
    "メガカエンジシ":           "pyroar-mega",
    "メガニャオニクス":         "meowstic-mega",
    "メガカラマネロ":           "malamar-mega",
    "メガガメノデス":           "barbaracle-mega",
    "メガドラミドロ":           "dragalge-mega",
    "メガルチャブル":           "hawlucha-mega",
    "メガサーナイト":           "gardevoir-mega",
    "メガユキノオー":           "abomasnow-mega",
    # gen 6 legendary/mythical
    "メガダークライ":           "darkrai-mega",
    "メガディアンシー":         "diancie-mega",
    # gen 7+ / gen9 fan-made (not in PokeAPI — handled via smogon calc)
    "メガライチュウＸ":         "raichu-mega-x",
    "メガライチュウＹ":         "raichu-mega-y",
    "メガゼラオラ":             "zeraora-mega",
    "メガタイレーツ":           "falinks-mega",
    "メガスコヴィラン":         "scovillain-mega",
    "メガキラフロル":           "glimmora-mega",
    "メガセグレイブ":           "baxcalibur-mega",
    "メガケケンカニ":           "crabominable-mega",
    "メガグソクムシャ":         "golisopod-mega",
    "メガジジーロン":           "drampa-mega",
    "メガマギアナ":             "magearna-mega",
    "メガフラエッテ":           "floette-mega",
    "ゲンシグラードン":         "groudon-primal",
    "ゲンシカイオーガ":         "kyogre-primal",
    "メガレックウザ":           "rayquaza-mega",
    "ギルガルド":                        "aegislash-shield",
    "ギルガルド (ブレードフォルム)":     "aegislash-blade",
    "チェリム (ポジフォルム)":           "cherrim-sunshine",
    "メロエッタ (ステップフォルム)":     "meloetta-pirouette",
    "ヒヒダルマ":                        "darmanitan-standard",
    "ヒヒダルマ (ダルマモード)":         "darmanitan-zen",
    "ヒヒダルマ (ガラルのすがた)":       "darmanitan-galar-standard",
    "ヒヒダルマ (ガラルのすがた・ダルマモード)": "darmanitan-galar-zen",
    "ガラルヒヒダルマ":                  "darmanitan-galar-standard",
    "ガラルヒヒダルマ (ダルマモード)":   "darmanitan-galar-zen",
    "オーガポン":                        "ogerpon",
    "オーガポン (いどのめん)":           "ogerpon-wellspring-mask",
    "オーガポン (かまどのめん)":         "ogerpon-hearthflame-mask",
    "オーガポン (いしずえのめん)":       "ogerpon-cornerstone-mask",
    "ジガルデ":                          "zygarde-50",
    "ジガルデ (１０％フォルム)":         "zygarde-10",
    "ジガルデ (パーフェクトフォルム)":   "zygarde-complete",
    "モルペコ":                          "morpeko-full-belly",
    "モルペコ (はらぺこもよう)":         "morpeko-hangry",
    "コオリッポ":                        "eiscue-ice",
    "コオリッポ (ナイスフェイス)":       "eiscue-noice",
    "メテノ":                            "minior-red-meteor",
    "メテノ (あかいろのコア)":           "minior-red",
    "ヨワシ":                            "wishiwashi-solo",
    "ヨワシ (むれたすがた)":             "wishiwashi-school",
    "イルカマン":                        "palafin-zero",
    "イルカマン (マイティフォルム)":     "palafin-hero",
    "テラパゴス":                        "terapagos-normal",
    "テラパゴス (テラスタルフォルム)":   "terapagos-terastal",
    "テラパゴス (ステラフォルム)":       "terapagos-stellar",
    "ポワルン (たいようのすがた)":       "castform-sunny",
    "ポワルン (あまみずのすがた)":       "castform-rainy",
    "ポワルン (ゆきぐものすがた)":       "castform-snowy",
    "ギラティナ(オリジンフォルム)":      "giratina-origin",
    "シェイミ(スカイフォルム)":          "shaymin-sky",
    "ヒートロトム":                      "rotom-heat",
    "ウォッシュロトム":                  "rotom-wash",
    "フロストロトム":                    "rotom-frost",
    "スピンロトム":                      "rotom-fan",
    "カットロトム":                      "rotom-mow",
    "デオキシス(アタックフォルム)":      "deoxys-attack",
    "デオキシス(ディフェンスフォルム)":  "deoxys-defense",
    "デオキシス(スピードフォルム)":      "deoxys-speed",
    "たそがれのたてがみネクロズマ":      "necrozma-dusk-mane",
    "あかつきのつばさネクロズマ":        "necrozma-dawn-wings",
    # Floette eternal flower — use PokeAPI name "floette-eternal" (ID 10061).
    # The Mega is NOT registered here; it is handled via FORM_MISSING_MEGA_STATS in _apply_form.
    "フラエッテ (えいえんのはな)":       "floette-eternal",
    "フラエッテ(えいえんのはな)":        "floette-eternal",
    "フラエッテ(えいえん)":              "floette-eternal",
    "フラエッテ (えいえん)":             "floette-eternal",
}

# Ability (Japanese) overrides for forms that change ability
FORM_ABILITY_JA: dict[str, str] = {
    # gen 1 megas
    "メガフシギバナ":   "あついしぼう",
    "メガリザードンＸ": "かたいツメ",
    "メガリザードンＹ": "ひでり",
    "メガカメックス":   "メガランチャー",
    "メガスピアー":     "てきおうりょく",
    "メガピジョット":   "ノーガード",
    "メガピクシー":     "マジックミラー",
    "メガウツボット":   "とびだすなかみ",
    "メガフーディン":   "トレース",
    "メガゲンガー":     "かげふみ",
    "メガスターミー":   "ちからもち",
    "メガカイロス":     "スカイスキン",
    "メガヤドラン":     "シェルアーマー",
    "メガガルーラ":     "おやこあい",
    "メガギャラドス":   "かたやぶり",
    "メガプテラ":       "かたいツメ",
    "メガカイリュー":   "マルチスケイル",
    "メガミュウツーＸ": "ふくつのこころ",
    "メガミュウツーＹ": "ふみん",
    # gen 2 megas
    "メガメガニウム":   "メガソーラー",
    "メガオーダイル":   "ドラゴンスキン",
    "メガデンリュウ":   "かたやぶり",
    "メガハガネール":   "すなのちから",
    "メガハッサム":     "テクニシャン",
    "メガヘラクロス":   "スキルリンク",
    "メガエアームド":   "すじがねいり",
    "メガヘルガー":     "サンパワー",
    "メガバンギラス":   "すなおこし",
    # gen 3 megas
    "メガジュカイン":   "ひらいしん",
    "メガバシャーモ":   "かそく",
    "メガラグラージ":   "すいすい",
    "メガサーナイト":   "フェアリースキン",
    "メガヤミラミ":     "マジックミラー",
    "メガクチート":     "ちからもち",
    "メガボスゴドラ":   "フィルター",
    "メガチャーレム":   "ヨガパワー",
    "メガライボルト":   "いかく",
    "メガサメハダー":   "がんじょうあご",
    "メガバクーダ":     "ちからずく",
    "メガチルタリス":   "フェアリースキン",
    "メガジュペッタ":   "いたずらごころ",
    "メガチリーン":     "ふゆう",
    "メガアブソル":     "マジックミラー",
    "メガオニゴーリ":   "フリーズスキン",
    "メガボーマンダ":   "スカイスキン",
    "メガメタグロス":   "かたいツメ",
    "メガラティアス":   "ふゆう",
    "メガラティオス":   "ふゆう",
    # gen 4 megas
    "メガルカリオ":     "てきおうりょく",
    "メガガブリアス":   "すなのちから",
    "メガミミロップ":   "きもったま",
    "メガユキノオー":   "ゆきふらし",
    "メガエルレイド":   "せいしんりょく",
    "メガユキメノコ":   "ゆきふらし",
    "メガムクホーク":   "いかく",
    "メガヒードラン":   "もらいび",
    "メガダークライ":   "ナイトメア",
    # gen 5 megas
    "メガエンブオー":   "かたやぶり",
    "メガドリュウズ":   "かんつうドリル",
    "メガタブンネ":     "いやしのこころ",
    "メガペンドラー":   "どくのトゲ",
    "メガズルズキン":   "だっぴ",
    "メガシビルドン":   "ふゆう",
    "メガシャンデラ":   "すりぬけ",
    "メガゴルーグ":     "ふかしのこぶし",
    # gen 6 megas
    "メガブリガロン":   "ぼうだん",
    "メガマフォクシー": "ふゆう",
    "メガゲッコウガ":   "へんげんじざい",
    "メガカエンジシ":   "じしんかじょう",
    "メガフラエッテ":   "フェアリーオーラ",
    "メガニャオニクス":  "トレース",
    "メガカラマネロ":   "あまのじゃく",
    "メガガメノデス":   "かたいツメ",
    "メガドラミドロ":   "どくのトゲ",
    "メガルチャブル":   "ノーガード",
    "メガディアンシー": "マジックミラー",
    # gen 7+ 
    "メガライチュウＸ": "サーフテール",
    "メガライチュウＹ": "サーフテール",
    "メガケケンカニ":   "てつのこぶし",
    "メガグソクムシャ": "にげごし",
    "メガジジーロン":   "ぎゃくじょう",
    "メガマギアナ":     "ソウルハート",
    "メガゼラオラ":     "ちくでん",
    "メガタイレーツ":   "カブトアーマー",
    "メガスコヴィラン": "とびだすハバネロ",
    "メガキラフロル":   "てきおうりょく",
    "メガシャリタツ":   "よびみず",
    "メガセグレイブ":   "ねつこうかん",
    # primals
    "ゲンシグラードン": "おわりのだいち",
    "ゲンシカイオーガ": "はじまりのうみ",
    "メガレックウザ":   "エアロック",
    "メガジガルデ": "スワームチェンジ",
    # battle-only form changes with ability change
    "ヒヒダルマ (ダルマモード)":              "ダルマモード",
    "ヒヒダルマ (ガラルのすがた・ダルマモード)": "ダルマモード",
    "テラパゴス":                             "テラスチェンジ",
    "テラパゴス (テラスタルフォルム)":        "テラスシェル",
    "テラパゴス (ステラフォルム)":            "ゼロフォーミング",
    "オーガポン":                             "みどりのめん",
    "オーガポン (いどのめん)":               "いどのめん",
    "オーガポン (かまどのめん)":             "かまどのめん",
    "オーガポン (いしずえのめん)":           "いしずえのめん",
}

# Stats for Mega forms absent from PokeAPI (gen9 fan-made / unreleased).
# Key: Smogon species name.  Value: (name_en, type1, type2, hp, atk, def, spa, spd, spe, weight_kg)
FORM_MISSING_MEGA_STATS: dict[str, tuple] = {
    "Absol-Mega-Z":           ("absol-mega-z",           "dark",    "ghost",    65,  154, 60,  75,  60,  151, 49.0),
    "Barbaracle-Mega":        ("barbaracle-mega",         "rock",    "fighting", 72,  140, 130, 64,  106, 88,  100.0),
    "Baxcalibur-Mega":        ("baxcalibur-mega",         "dragon",  "ice",      115, 175, 117, 105, 101, 87,  315.0),
    "Chandelure-Mega":        ("chandelure-mega",         "ghost",   "fire",     60,  75,  110, 175, 110, 90,  69.6),
    "Chesnaught-Mega":        ("chesnaught-mega",         "grass",   "fighting", 88,  137, 172, 74,  115, 44,  90.0),
    "Chimecho-Mega":          ("chimecho-mega",           "psychic", "steel",    75,  50,  110, 135, 120, 65,  8.0),
    "Clefable-Mega":          ("clefable-mega",           "fairy",   "flying",   95,  80,  93,  135, 110, 70,  42.3),
    "Crabominable-Mega":      ("crabominable-mega",       "fighting","ice",      97,  157, 122, 62,  107, 33,  252.8),
    "Darkrai-Mega":           ("darkrai-mega",            "dark",    "",         70,  120, 130, 165, 130, 85,  240.0),
    "Delphox-Mega":           ("delphox-mega",            "fire",    "psychic",  75,  69,  72,  159, 125, 134, 39.0),
    "Dragalge-Mega":          ("dragalge-mega",           "poison",  "dragon",   65,  85,  105, 132, 163, 44,  100.3),
    "Dragonite-Mega":         ("dragonite-mega",          "dragon",  "flying",   91,  124, 115, 145, 125, 100, 290.0),
    "Drampa-Mega":            ("drampa-mega",             "normal",  "dragon",   78,  85,  110, 160, 116, 36,  185.0),
    "Eelektross-Mega":        ("eelektross-mega",         "electric","",         85,  145, 80,  135, 90,  80,  160.0),
    "Emboar-Mega":            ("emboar-mega",             "fire",    "fighting", 110, 148, 75,  110, 110, 75,  180.3),
    "Excadrill-Mega":         ("excadrill-mega",          "ground",  "steel",    110, 165, 100, 65,  65,  103, 60.0),
    "Falinks-Mega":           ("falinks-mega",            "fighting","",         65,  135, 135, 70,  65,  100, 99.0),
    "Feraligatr-Mega":        ("feraligatr-mega",         "water",   "dragon",   85,  160, 125, 89,  93,  78,  108.8),
    "Floette-Mega":           ("floette-mega",            "fairy",   "",         74,  85,  87,  155, 148, 102, 100.8),
    "Froslass-Mega":          ("froslass-mega",           "ice",     "ghost",    70,  80,  70,  140, 100, 120, 29.6),
    "Garchomp-Mega-Z":        ("garchomp-mega-z",         "dragon",  "",         108, 130, 85,  141, 85,  151, 99.0),
    "Glimmora-Mega":          ("glimmora-mega",           "rock",    "poison",   83,  90,  105, 150, 96,  101, 77.0),
    "Golisopod-Mega":         ("golisopod-mega",          "bug",     "steel",    75,  150, 175, 70,  120, 40,  148.0),
    "Golurk-Mega":            ("golurk-mega",             "ground",  "ghost",    89,  159, 105, 70,  105, 55,  330.0),
    "Greninja-Mega":          ("greninja-mega",           "water",   "dark",     72,  125, 77,  133, 81,  142, 40.0),
    "Hawlucha-Mega":          ("hawlucha-mega",           "fighting","flying",   78,  137, 100, 74,  93,  118, 25.0),
    "Heatran-Mega":           ("heatran-mega",            "fire",    "steel",    91,  120, 106, 175, 141, 67,  570.0),
    "Lucario-Mega-Z":         ("lucario-mega-z",          "fighting","steel",    70,  100, 70,  164, 70,  151, 49.4),
    "Magearna-Mega":          ("magearna-mega",           "steel",   "fairy",    80,  125, 115, 170, 115, 95,  248.1),
    "Magearna-Original-Mega": ("magearna-original-mega",  "steel",   "fairy",    80,  125, 115, 170, 115, 95,  248.1),
    "Malamar-Mega":           ("malamar-mega",            "dark",    "psychic",  86,  102, 88,  98,  120, 88,  69.8),
    "Meganium-Mega":          ("meganium-mega",           "grass",   "fairy",    80,  92,  115, 143, 115, 80,  201.0),
    "Meowstic-F-Mega":        ("meowstic-f-mega",         "psychic", "",         74,  48,  76,  143, 101, 124, 10.1),
    "Meowstic-M-Mega":        ("meowstic-m-mega",         "psychic", "",         74,  48,  76,  143, 101, 124, 10.1),
    "Pyroar-Mega":            ("pyroar-mega",             "fire",    "normal",   86,  88,  92,  129, 86,  126, 93.3),
    "Raichu-Mega-X":          ("raichu-mega-x",           "electric","",         60,  135, 95,  90,  95,  110, 38.0),
    "Raichu-Mega-Y":          ("raichu-mega-y",           "electric","",         60,  100, 55,  160, 80,  130, 26.0),
    "Scolipede-Mega":         ("scolipede-mega",          "bug",     "poison",   60,  140, 149, 75,  99,  62,  230.5),
    "Scovillain-Mega":        ("scovillain-mega",         "grass",   "fire",     65,  138, 85,  138, 85,  75,  22.0),
    "Scrafty-Mega":           ("scrafty-mega",            "dark",    "fighting", 65,  130, 135, 55,  135, 68,  31.0),
    "Skarmory-Mega":          ("skarmory-mega",           "steel",   "flying",   65,  140, 110, 40,  100, 110, 40.4),
    "Staraptor-Mega":         ("staraptor-mega",          "fighting","flying",   85,  140, 100, 60,  90,  110, 50.0),
    "Starmie-Mega":           ("starmie-mega",            "water",   "psychic",  60,  140, 105, 130, 105, 120, 80.0),
    "Tatsugiri-Curly-Mega":   ("tatsugiri-curly-mega",    "dragon",  "water",    68,  65,  90,  135, 125, 92,  8.0),
    "Tatsugiri-Droopy-Mega":  ("tatsugiri-droopy-mega",   "dragon",  "water",    68,  65,  90,  135, 125, 92,  8.0),
    "Tatsugiri-Stretchy-Mega":("tatsugiri-stretchy-mega", "dragon",  "water",    68,  65,  90,  135, 125, 92,  8.0),
    "Victreebel-Mega":        ("victreebel-mega",         "grass",   "poison",   80,  125, 85,  135, 95,  70,  125.5),
    "Zeraora-Mega":           ("zeraora-mega",            "electric","",         88,  157, 75,  147, 80,  153, 44.5),
    "Zygarde-Mega":           ("zygarde-mega",            "dragon",  "ground",   216, 70,  91,  216, 85,  100, 610.0),
}
